# -*- coding: utf-8 -*-
"""LING360_Assignment1_AhmetAltarLuser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15gS_kH1O0HRPTKWuwJGZ9sSGWH9f2wHI

# Assignment 1

This is the <font color='cyan'>Assignment 1</font> for the LING360 - Computational Methods in Lingustics course and it is worth a total of  <font color='cyan'>**5 points**</font>.
The assignment covers the basic knowledge of Python. 

The topics include:
1. Variables
2. String Operations
3. List indexing

There's a total of  <font color='cyan'>**3 main tasks**</font>. For each task, please write your code between the following lines:

```
## YOUR CODE STARTS


## YOUR CODE ENDS
```

Before working on the assignment, please copy this notebook to your own drive. You can use ```Save a copy in Drive``` under the ```File``` menu on top left.

Please, run every cell in your code to make sure that it works properly before submitting it. 

Once you are ready to submit, download two versions of your code:

*   Download .ipynb
*   Download .py

These are both available under the ```File``` menu on top left. 

Then, compress your files (zip, rar, or whatever) and upload the compressed file to Moodle.

If you have any questions, please contact karahan.sahin@boun.edu.tr

<font color='#FFBD33'>**Q1:**</font> Create a variable called `my_name` and print it with `print` function. 


`(0.5 Points)`
"""

## YOUR CODE STARTS
my_name = "Altar"
print(my_name)

## YOUR CODE ENDS

"""<font color='#FFBD33'>**Q2:**</font> Create a variable called my_introduction which says **"Hello, my name is `my_name`"** and print it print it with `print` function. 

`(0.5 Points)`
"""

## YOUR CODE STARTS
my_introduction = f"Hello, my name is {my_name}"
print(my_introduction)

## YOUR CODE ENDS

"""<font color='#FFBD33'>**Q3:**</font> Create a variable called `my_friends` which contains three names and print **"Hello `friend-name`, my name is `my_name`"**  for each name by accessing with indices.  

`(0.5 Points)`
"""

## YOUR CODE STARTS
my_friends = ["Uğur", "Defne", "Can"]
print("Hello " + my_friends[0] + ", my name is " + my_name)
print("Hello " + my_friends[1] + ", my name is " + my_name)
print("Hello " + my_friends[2] + ", my name is " + my_name)
## YOUR CODE ENDS

"""<font color='#FFBD33'>**Q4:**</font> Reveal the secret message by slicing the string. **Instructions** are:  
1. Start from **2<sup>nd</sup>** character
2. Until **45<sup>th</sup>** character
3. Skip by every **3** characters
4. Finally `print` the slicing


`(1.5 Points)`
"""

SECRET_MESSAGE = "HPNGOHCLBFOBCNMXEEJZMZKBRÖZAYAMDUREORYQEİLEMFQDHSJSDFKSJDBHFSKJLK"
## YOUR CODE STARTS
print(SECRET_MESSAGE[1:45:3])

## YOUR CODE ENDS

"""<font color='#FFBD33'>**Q5:**</font> Create your own secret message this time!

**Instructions are:**

1. First create a secret message string by adding random characters between each character of your message. For example:
```python
# This is formatted as code
MESSAGE = "AMD"
YOUR_SECRET_MESSAGE = MESSAGE[0] + "DKS" + MESSAGE[1] + "XYZ" + MESSAGE[2] + "ABC"
# YOUR SECRET MESSAGE should be "ADKSMXYZDABC"
````
2. Instead of writing random characters, you can call `create_random_characters()` function to generate random letters
3. After creating your secret message, please provide a `start`, `stop`, and `increment` info to decipher your string by slicing.
4. At the end, your slicing operation on `YOUR_SECRET_MESSAGE` should yield the same value with `YOUR_MESSAGE`


**Notes:**
1. Please note that random characters are at same length! Your random characters should be at same length in order to increment operator can work.
2. Your increment value must be bigger than 1.


`(2 Points)`
"""

# YOU MUST RUN THIS LINE

# The code in below creates random string with NUMBER_OF_RANDOM_CHARACTERS of letters
# Eg. -> random_letters="XYQ" if NUMBER_OF_RANDOM_CHARACTERS=3
import random
import string
def create_random_characters(NUMBER_OF_RANDOM_CHARACTERS):
  return "".join(random.choices(string.ascii_uppercase, 
                                k=NUMBER_OF_RANDOM_CHARACTERS))

# Example usage
print("Created 2 random characters are:",create_random_characters(2))
print("Created 3 random characters are:",create_random_characters(3))
print("Created 5 random characters are:",create_random_characters(5))

## YOUR CODE STARTS (DO NOT EDIT ABOVE)
YOUR_MESSAGE = "GEZİCİ"
YOUR_SECRET_MESSAGE = YOUR_MESSAGE[0] + "QKZ" + YOUR_MESSAGE[1] + "PNZ" + YOUR_MESSAGE[2] + "QWJ" + YOUR_MESSAGE[3] + "XEN" + YOUR_MESSAGE[4] + "JBT" + YOUR_MESSAGE[5] + "GKY"

start = 0
stop = 23
increment = 4
## YOUR CODE ENDS (DO NOT EDIT BELOW)

if YOUR_SECRET_MESSAGE[start: stop: increment] == YOUR_MESSAGE:
  print("Your secret message is correctly encryted!")
else:
  print("Your secret message is incorrectly encryted! Please check your code again!")